#!/usr/bin/env node
// GitHub Action wrapper for env-diff
// Reads inputs from environment variables (GITHUB_* and INPUT_*)
// Zero dependency on @actions/core — uses native GitHub Actions env protocol

import * as fs from "fs";
import * as path from "path";
import { parseEnvFile } from "../src/parser.js";
import { diffEnvironmentMaps } from "../src/differ.js";
import { formatJson, formatMarkdown, formatTable, formatSummary } from "../src/formatters.js";
import { isSecretKey, maskValue } from "../src/secrets.js";
import type { DiffResult, DiffEntry, DiffOptions, ValueType } from "../src/types.js";

// ---------------------------------------------------------------------------
// GitHub Actions I/O helpers (no @actions/core dependency)
// ---------------------------------------------------------------------------

function getInput(name: string): string {
  return process.env[`INPUT_${name.toUpperCase().replace(/-/g, "_")}`] ?? "";
}

function setOutput(name: string, value: string): void {
  const outputFile = process.env["GITHUB_OUTPUT"];
  if (outputFile) {
    // Use delimiter protocol for multi-line safe output
    if (value.includes("\n")) {
      const delimiter = `ghadelimiter_${Date.now()}`;
      fs.appendFileSync(outputFile, `${name}<<${delimiter}\n${value}\n${delimiter}\n`);
    } else {
      fs.appendFileSync(outputFile, `${name}=${value}\n`);
    }
  }
}

function writeSummary(content: string): void {
  const summaryFile = process.env["GITHUB_STEP_SUMMARY"];
  if (summaryFile) {
    fs.appendFileSync(summaryFile, content + "\n");
  }
}

// ---------------------------------------------------------------------------
// Secret masking — creates a deep copy of the result with masked values
// ---------------------------------------------------------------------------

function maskResultSecrets(result: DiffResult): DiffResult {
  const maskedEntries: DiffEntry[] = result.entries.map((entry) => {
    if (!isSecretKey(entry.key)) {
      return entry;
    }

    return {
      key: entry.key,
      left: entry.left !== undefined ? maskValue(entry.left) : undefined,
      right: entry.right !== undefined ? maskValue(entry.right) : undefined,
      status: entry.status,
      severity: entry.severity,
    };
  });

  return {
    entries: maskedEntries,
    leftLabel: result.leftLabel,
    rightLabel: result.rightLabel,
    hasErrors: result.hasErrors,
    hasWarnings: result.hasWarnings,
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function run(): void {
  const left = getInput("left");
  const right = getInput("right");
  const strict = getInput("strict") !== "false";
  const ignore = getInput("ignore")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  const format = getInput("format") || "table";
  const shouldMaskSecrets = getInput("mask-secrets") !== "false";

  if (!left || !right) {
    console.error("::error::Both 'left' and 'right' inputs are required");
    process.exit(1);
  }

  const leftPath = path.resolve(left);
  const rightPath = path.resolve(right);

  if (!fs.existsSync(leftPath)) {
    console.error(`::error::Left file not found: ${leftPath}`);
    process.exit(1);
  }
  if (!fs.existsSync(rightPath)) {
    console.error(`::error::Right file not found: ${rightPath}`);
    process.exit(1);
  }

  // Parse env files
  const leftEnv = parseEnvFile(leftPath);
  const rightEnv = parseEnvFile(rightPath);

  // Build diff options
  const options: DiffOptions = {
    ignoreKeys: ignore.length > 0 ? ignore : undefined,
  };

  // Compute diff
  const rawResult = diffEnvironmentMaps(leftEnv, rightEnv, left, right, options);

  // Optionally mask secrets for display
  const result = shouldMaskSecrets ? maskResultSecrets(rawResult) : rawResult;

  // Count by status
  let added = 0;
  let removed = 0;
  let modified = 0;
  let unchanged = 0;
  let typeMismatch = 0;

  for (const e of result.entries) {
    switch (e.status) {
      case "added":
        added++;
        break;
      case "removed":
        removed++;
        break;
      case "modified":
        modified++;
        break;
      case "unchanged":
        unchanged++;
        break;
      case "type-mismatch":
        typeMismatch++;
        break;
    }
  }

  // Set outputs
  setOutput("has-errors", String(result.hasErrors));
  setOutput("has-warnings", String(result.hasWarnings));
  setOutput("added-count", String(added));
  setOutput("removed-count", String(removed));
  setOutput("json-result", formatJson(result));

  // Write GitHub step summary (always markdown)
  writeSummary("## env-diff Results\n");
  writeSummary(formatMarkdown(result));
  writeSummary(
    `\n*Generated by [env-diff](https://github.com/AdametherzLab/env-diff) by AdametherzLab | Built with Claude*`
  );

  // Console output in requested format
  switch (format) {
    case "json":
      console.log(formatJson(result));
      break;
    case "markdown":
      console.log(formatMarkdown(result));
      break;
    case "summary":
      console.log(formatSummary(result));
      break;
    default:
      console.log(formatTable(result));
      break;
  }

  // Strict mode: fail if errors detected
  if (strict && result.hasErrors) {
    console.error("::error::Environment check failed with errors");
    process.exit(1);
  }
}

run();
